import { User, Transaction, Insight } from "./types";

export const mockUser: User = {
  name: "Ahmet",
  avatar: "/" + encodeURIComponent("profile photo.png"),
  thisMonthSpend: 8420,
  lastMonthSpend: 7100,
  delta: +18.6,
};

export const mockTransactions: Transaction[] = [
  // ── Bugün ──
  {
    id: "txn_001",
    merchant: "Getir",
    category: "Market",
    amount: -149,
    currency: "TRY",
    date: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 saat önce
    source: "gmail",
    logoUrl: "/" + encodeURIComponent("getir logo .png"),
  },
  {
    id: "txn_002",
    merchant: "Starbucks",
    category: "Kahve",
    amount: -125,
    currency: "TRY",
    date: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 saat önce
    source: "bank",
    logoUrl: "/Starbucks_Corporation_Logo_2011.svg.png",
  },
  {
    id: "txn_003",
    merchant: "Uber",
    category: "Ulaşım",
    amount: -87,
    currency: "TRY",
    date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    source: "bank",
    logoUrl: "/1659761297uber-icon.png",
  },

  // ── Dün ──
  {
    id: "txn_004",
    merchant: "Spotify",
    category: "Abonelik",
    amount: -59.99,
    currency: "TRY",
    date: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/Spotify_logo_without_text.svg.png",
  },
  {
    id: "txn_005",
    merchant: "Migros",
    category: "Market",
    amount: -312,
    currency: "TRY",
    date: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    source: "bank",
    logoUrl: "/M.png",
  },
  {
    id: "txn_006",
    merchant: "Bolt",
    category: "Ulaşım",
    amount: -64,
    currency: "TRY",
    date: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
    source: "manual",
    logoUrl: "/Bolt_logo.png",
  },

  // ── 2 Gün Önce ──
  {
    id: "txn_007",
    merchant: "Domino's",
    category: "Yemek",
    amount: -189,
    currency: "TRY",
    date: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/" + encodeURIComponent("Domino's_pizza_logo.svg.png"),
  },
  {
    id: "txn_008",
    merchant: "Netflix",
    category: "Abonelik",
    amount: -89.99,
    currency: "TRY",
    date: new Date(Date.now() - 54 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/netflix.png",
  },
  {
    id: "txn_009",
    merchant: "Trendyol",
    category: "Market",
    amount: -455,
    currency: "TRY",
    date: new Date(Date.now() - 56 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/" + encodeURIComponent("trendyol logo.png"),
  },
  {
    id: "txn_010",
    merchant: "Tchibo",
    category: "Kahve",
    amount: -78,
    currency: "TRY",
    date: new Date(Date.now() - 58 * 60 * 60 * 1000).toISOString(),
    source: "bank",
    logoUrl: "/Tchibo_logo.png",
  },

  // ── 4 Gün Önce ──
  {
    id: "txn_011",
    merchant: "Getir",
    category: "Market",
    amount: -213,
    currency: "TRY",
    date: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/" + encodeURIComponent("getir logo .png"),
  },
  {
    id: "txn_012",
    merchant: "IETT",
    category: "Ulaşım",
    amount: -200,
    currency: "TRY",
    date: new Date(Date.now() - 98 * 60 * 60 * 1000).toISOString(),
    source: "bank",
    logoUrl: "/IETT.PNG",
  },

  // ── 6 Gün Önce ──
  {
    id: "txn_013",
    merchant: "Apple Music",
    category: "Abonelik",
    amount: -49.99,
    currency: "TRY",
    date: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/Apple_Music_icon.svg.png",
  },
  {
    id: "txn_014",
    merchant: "Caribou Coffee",
    category: "Kahve",
    amount: -95,
    currency: "TRY",
    date: new Date(Date.now() - 146 * 60 * 60 * 1000).toISOString(),
    source: "bank",
    logoUrl: "/Caribou1.svg",
  },
  {
    id: "txn_015",
    merchant: "Uber Eats",
    category: "Yemek",
    amount: -245,
    currency: "TRY",
    date: new Date(Date.now() - 148 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/" + encodeURIComponent("uber eats.png"),
  },
  {
    id: "txn_016",
    merchant: "Turkcell",
    category: "Fatura",
    amount: -425,
    currency: "TRY",
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    source: "gmail",
    logoUrl: "/AMBLEM_SARI.jpg.webp",
  },
];

export const mockInsights: Insight[] = [
  {
    id: "ins_trial_001",
    type: "tip",
    text: "YouTube Premium deneme süren 3 gün sonra bitiyor. İptal etmezsen 59.99 ₺ çekilecek.",
    icon: "alert-triangle",
    severity: "warning",
    paymentAmountTry: 59.99,
    action: { label: "Hafızada gör", tab: "insights" },
  },
  {
    id: "ins_sub_001",
    type: "memory",
    text: "Turkcell faturan geçen aya göre %20 arttı (Aşım ücreti: 85 ₺).",
    icon: "brain",
    severity: "warning",
    paymentAmountTry: 85,
  },
  {
    id: "ins_001",
    type: "trend",
    text: "Bu ay Getir'e geçen aya göre %35 fazla harcadın. Bu hızla devam ederse aylık 800₺'yi aşabilir.",
    icon: "trending-up",
    severity: "warning",
    paymentAmountTry: 800,
    action: { label: "Harcamalara git", tab: "expenses" },
  },
  {
    id: "ins_002",
    type: "memory",
    text: "Kasım'dan beri Spotify'a aylık 59,99₺ ödüyorsun ama son 28 gündür hiç açmamışsın.",
    icon: "brain",
    severity: "warning",
    paymentAmountTry: 59.99,
  },
  {
    id: "ins_price_001",
    type: "tip",
    text: "Netflix üyelik ücretine %15 zam geliyor. Yeni dönemde bu tutar çekilecek.",
    icon: "sparkles",
    severity: "info",
    paymentAmountTry: 114.99,
  },
];
