export {
  Home,
  PieChart,
  History as Brain,
  User,
  Magnifer as Search,
  Plain as Send,
  Microphone as Mic,
  CloseCircle as X,
  AltArrowLeft as ChevronLeft,
  AltArrowRight as ChevronRight,
  Filter,
  Bill as Receipt,
  Tuning as SlidersHorizontal,
  AddCircle as Plus,
  CupHot as Coffee,
  Cart as ShoppingCart,
  ChefHat as Utensils,
  Wheel as Car,
  MusicNote as Music,
  Card as CreditCard,
  Wallet,
  Letter as Mail,
  Banknote as Landmark,
  ArrowRight,
  Logout as LogOut,
  Bell,
  Shield,
  Moon,
  Sun,
  Lightbulb,
  DangerCircle as AlertCircle,
  CheckCircle,
  Dumbbell,
  Gamepad as Gamepad2,
} from "@solar-icons/react"
